services:
  web:
    build: .
    ports:
      - "8000:5000"
    environment:
      FLASK_DEBUG: "true"
    volumes:
      - .:/code
      - logvolume01:/var/log
    depends_on:
      - redis

  redis:
    image: redis

volumes:
  logvolume01: {}